server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html/test-reports;
    index index.html;

    autoindex off;
    charset utf-8;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /backend/jacoco/ {
        alias /usr/share/nginx/html/test-reports/backend/jacoco/;
        index index.html;
    }

    location /backend/surefire/ {
        alias /usr/share/nginx/html/test-reports/backend/surefire/;
        autoindex on;
    }

    location /frontend/coverage/ {
        alias /usr/share/nginx/html/test-reports/frontend/coverage/;
        index index.html;
    }

    add_header Cache-Control "no-store, no-cache, must-revalidate";
}
